import pandas as pd
from sdv import Metadata


class BaseSDV:

    def __init__(self, metadata: Metadata):
        self.metadata = metadata

    def _get_df_csv(self) -> pd.DataFrame:
        """
        :return: pandas dataframe
        """
        raise NotImplementedError

    @staticmethod
    def _get_fields_metadata() -> dict:
        """
        Fields metadata is used to override the actual metadata generated by sdv.
        Eg.
        {
            "join_date": {
                'type': 'datetime',
                'format': '%Y-%m-%d'
            },
            "first_name": {
                'type': 'categorical',
                'pii': True,
                'pii_category': 'first_name'
            }
        }

        :return: a dictionary of custom table field metadata
        """
        raise NotImplementedError

    def get_df_and_metadata(self) -> [pd.DataFrame, Metadata]:
        """
        data frame from which sdv will determine the metadata, same data will be used for training purpose later
        :return: a training dataframe, generated metadata
        """

        raise NotImplementedError
